//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetTips.Spargine.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetTips.Spargine.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AES Decryption Failed..
        /// </summary>
        internal static string AESDecryptionFailed {
            get {
                return ResourceManager.GetString("AESDecryptionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AES Encryption failed..
        /// </summary>
        internal static string AESEncryptionFailed {
            get {
                return ResourceManager.GetString("AESEncryptionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument cannot be null..
        /// </summary>
        internal static string ErrorArgumentNull {
            get {
                return ResourceManager.GetString("ErrorArgumentNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument is out of the given range..
        /// </summary>
        internal static string ErrorArgumentOutOfRange {
            get {
                return ResourceManager.GetString("ErrorArgumentOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection is null or has no items..
        /// </summary>
        internal static string ErrorCollectionIsNullOrHasNoItems {
            get {
                return ResourceManager.GetString("ErrorCollectionIsNullOrHasNoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection size is not valid..
        /// </summary>
        internal static string ErrorCollectionSizeIsNotValid {
            get {
                return ResourceManager.GetString("ErrorCollectionSizeIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date is invalid based on min/max range..
        /// </summary>
        internal static string ErrorDateIsInvalidBasedOnMinMaxDateTime {
            get {
                return ResourceManager.GetString("ErrorDateIsInvalidBasedOnMinMaxDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date is invalid based on the min / max range..
        /// </summary>
        internal static string ErrorDateIsInvalidBasedOnTheMinMaxRange {
            get {
                return ResourceManager.GetString("ErrorDateIsInvalidBasedOnTheMinMaxRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory does not exist..
        /// </summary>
        internal static string ErrorDirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("ErrorDirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified directory was not found..
        /// </summary>
        internal static string ErrorDirectoryNotFound {
            get {
                return ResourceManager.GetString("ErrorDirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is not defined in the Enum..
        /// </summary>
        internal static string ErrorEnumNotDefined {
            get {
                return ResourceManager.GetString("ErrorEnumNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found..
        /// </summary>
        internal static string ErrorFileNotFound {
            get {
                return ResourceManager.GetString("ErrorFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUID is empty..
        /// </summary>
        internal static string ErrorGUIDIsEmpty {
            get {
                return ResourceManager.GetString("ErrorGUIDIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guid is Nulll or Empty..
        /// </summary>
        internal static string ErrorGuidIsNullOrEmpty {
            get {
                return ResourceManager.GetString("ErrorGuidIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid argument..
        /// </summary>
        internal static string ErrorInvalidArgument {
            get {
                return ResourceManager.GetString("ErrorInvalidArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object could not be cast to a new type..
        /// </summary>
        internal static string ErrorInvalidCast {
            get {
                return ResourceManager.GetString("ErrorInvalidCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Enum type..
        /// </summary>
        internal static string ErrorInvalidEnumType {
            get {
                return ResourceManager.GetString("ErrorInvalidEnumType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid operation..
        /// </summary>
        internal static string ErrorInvalidOperation {
            get {
                return ResourceManager.GetString("ErrorInvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type..
        /// </summary>
        internal static string ErrorInvalidType {
            get {
                return ResourceManager.GetString("ErrorInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Value..
        /// </summary>
        internal static string ErrorInvalidValue {
            get {
                return ResourceManager.GetString("ErrorInvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List cannot be null or read-only..
        /// </summary>
        internal static string ErrorListCannotBeReadOnly {
            get {
                return ResourceManager.GetString("ErrorListCannotBeReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message could not be queued..
        /// </summary>
        internal static string ErrorMessageNotQueued {
            get {
                return ResourceManager.GetString("ErrorMessageNotQueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown network connection issue..
        /// </summary>
        internal static string ErrorNetworkConnectionIssue {
            get {
                return ResourceManager.GetString("ErrorNetworkConnectionIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number is invalid based on the min/max range..
        /// </summary>
        internal static string ErrorNumberIsInvalidBasedOnTheMinMaxValue {
            get {
                return ResourceManager.GetString("ErrorNumberIsInvalidBasedOnTheMinMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object cannot be null. Duh!.
        /// </summary>
        internal static string ErrorObjectCannotBeNull {
            get {
                return ResourceManager.GetString("ErrorObjectCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object must be of type {0}.
        /// </summary>
        internal static string ErrorObjectMustBeOfType {
            get {
                return ResourceManager.GetString("ErrorObjectMustBeOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection cannot be read-only..
        /// </summary>
        internal static string ErrorReadOnlyCollection {
            get {
                return ResourceManager.GetString("ErrorReadOnlyCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadOnlySpan cannot be null or empty..
        /// </summary>
        internal static string ErrorReadOnlySpanCannotBeNull {
            get {
                return ResourceManager.GetString("ErrorReadOnlySpanCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of Span&lt;T&gt; cannot be empty..
        /// </summary>
        internal static string ErrorSpanCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("ErrorSpanCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Span is empty..
        /// </summary>
        internal static string ErrorSpanIsEmpty {
            get {
                return ResourceManager.GetString("ErrorSpanIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String is not valid..
        /// </summary>
        internal static string ErrorStringIsNotValid {
            get {
                return ResourceManager.GetString("ErrorStringIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String is Null or Empty..
        /// </summary>
        internal static string ErrorStringIsNullOrEmpty {
            get {
                return ResourceManager.GetString("ErrorStringIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error with Json serialization..
        /// </summary>
        internal static string ErrorThereWasAnErrorWithJsonSerialization {
            get {
                return ResourceManager.GetString("ErrorThereWasAnErrorWithJsonSerialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time is invalid based on the min/max range..
        /// </summary>
        internal static string ErrorTimeIsInvalidBasedOnTheMinMaxRange {
            get {
                return ResourceManager.GetString("ErrorTimeIsInvalidBasedOnTheMinMaxRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown IO Exception..
        /// </summary>
        internal static string ErrorUnknownIOException {
            get {
                return ResourceManager.GetString("ErrorUnknownIOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uri cannot be null..
        /// </summary>
        internal static string ErrorUriCannotBeNull {
            get {
                return ResourceManager.GetString("ErrorUriCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to deserialize countries data..
        /// </summary>
        internal static string FailedToDeserializeCountriesData {
            get {
                return ResourceManager.GetString("FailedToDeserializeCountriesData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found. Cannot deserialize from JSON..
        /// </summary>
        internal static string FileNotFoundCannotDeserializeFromJSON {
            get {
                return ResourceManager.GetString("FileNotFoundCannotDeserializeFromJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found. Cannot deserialize from XML..
        /// </summary>
        internal static string FileNotFoundCannotDeserializeFromXML {
            get {
                return ResourceManager.GetString("FileNotFoundCannotDeserializeFromXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to dotNetTips.com for help..
        /// </summary>
        internal static string MessageGoToDotNetTipsComForHelp {
            get {
                return ResourceManager.GetString("MessageGoToDotNetTipsComForHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network connection issue..
        /// </summary>
        internal static string NetworkConnectionIssue {
            get {
                return ResourceManager.GetString("NetworkConnectionIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more items to retrieve and the collection is not set to repeat..
        /// </summary>
        internal static string NoMoreItemsToRetrieveAndTheCollectionIsNot {
            get {
                return ResourceManager.GetString("NoMoreItemsToRetrieveAndTheCollectionIsNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebooting is only supported on Windows..
        /// </summary>
        internal static string RebootingIsOnlySupportedOnWindows {
            get {
                return ResourceManager.GetString("RebootingIsOnlySupportedOnWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*.
        /// </summary>
        internal static string RegexEmail {
            get {
                return ResourceManager.GetString("RegexEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (http|ftp|https):\/\/[\w\-_]+(\.[\w\-_]+)+([\w\-\.,@?^=%&amp;amp;:/~\+#]*[\w\-\@?^=%&amp;amp;/~\+#])?.
        /// </summary>
        internal static string RegexUrl {
            get {
                return ResourceManager.GetString("RegexUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index is equal to or greater than the length of the array, or the number of elements in the set is greater than the available space from index to the end of the destination array..
        /// </summary>
        internal static string TheIndexIsEqualToOrGreaterThanTheLengthOfInput {
            get {
                return ResourceManager.GetString("TheIndexIsEqualToOrGreaterThanTheLengthOfInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an issue adding an item in the collection.
        /// </summary>
        internal static string ThereWasAnIssueAddingAnItemInTheCollection {
            get {
                return ResourceManager.GetString("ThereWasAnIssueAddingAnItemInTheCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underlying collection is null..
        /// </summary>
        internal static string UnderlyingCollectionIsNull {
            get {
                return ResourceManager.GetString("UnderlyingCollectionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNKNOWN.
        /// </summary>
        internal static string UserUnknown {
            get {
                return ResourceManager.GetString("UserUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WorldCities {
            get {
                object obj = ResourceManager.GetObject("WorldCities", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
