//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetTips.Spargine.Core.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetTips.Spargine.Core.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Address1&quot;:&quot;kFMEXMxCCGDmSIYxBJVEXiqCE&quot;,&quot;Address2&quot;:&quot;LFywoulsFLk^YPDHViI_CUtLw&quot;,&quot;Age&quot;:&quot;5840.00:00:00.0350488&quot;,&quot;BornOn&quot;:&quot;2006-04-30T15:42:21.5603971-07:00&quot;,&quot;CellPhone&quot;:&quot;745-442-6873&quot;,&quot;City&quot;:&quot;[BOpiPKrU^IKyHl&quot;,&quot;Country&quot;:&quot;GeL[ot]CxI_V][b&quot;,&quot;Email&quot;:&quot;vsecutbwrvgmnglljry@dqijtmogvvbsxbs.band&quot;,&quot;FirstName&quot;:&quot;FZMxhsOFJvjUOcE&quot;,&quot;HomePhone&quot;:&quot;748-543-3086&quot;,&quot;Id&quot;:&quot;57026b9d8d8146959891e37579c73f39&quot;,&quot;LastName&quot;:&quot;MAqXlW^qJWFSCpMBuD^lbySnH&quot;,&quot;PostalCode&quot;:&quot;63835673&quot;,&quot;State&quot;:&quot;MKlm\u0060UEPc_IPRKX&quot;}.
        /// </summary>
        internal static string JsonPersonProper {
            get {
                return ResourceManager.GetString("JsonPersonProper", resourceCulture);
            }
        }
    }
}
