// ***********************************************************************
// Assembly         : DotNetTips.Spargine.8.Extensions
// Author           : David McCarter
// Created          : 11-21-2020
//
// Last Modified By : David McCarter
// Last Modified On : 07-11-2024
// ***********************************************************************
// <copyright file="DictionaryExtensions.cs" company="McCarter Consulting">
//     Copyright (c) David McCarter - dotNetTips.com. All rights reserved.
// </copyright>
// <summary>Extension methods for IDictionary types.</summary>
// ***********************************************************************
using System.Collections;
using System.Collections.Concurrent;
using System.Collections.Frozen;
using System.Collections.Immutable;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Globalization;
using System.Runtime.CompilerServices;
using System.Text;
using DotNetTips.Spargine.Core;
using Microsoft.Extensions.ObjectPool;

//`![Spargine 8 -  #RockYourCode](6219C891F6330C65927FA249E739AC1F.png;https://www.spargine.net )

namespace DotNetTips.Spargine.Extensions;

/// <summary>
/// Provides extension methods for <see cref="IDictionary{TKey, TValue}"/> to enhance dictionary functionality.
/// This includes methods for adding or updating entries, converting dictionaries to various forms,
/// disposing dictionary items, and more.
/// </summary>
public static class DictionaryExtensions
{

	/// <summary>
	/// The string builder pool
	/// </summary>
	private static readonly ObjectPool<StringBuilder> _stringBuilderPool = new DefaultObjectPoolProvider().CreateStringBuilderPool();

	/// <summary>
	/// Processes the specified collection to dispose its items.
	/// </summary>
	/// <param name="items">The collection of items to process for disposal.</param>
	/// <remarks>
	/// This method iterates over the collection and disposes each item that implements <see cref="IDisposable"/>.
	/// It's a utility method to ensure resources are properly released for collections of disposable items.
	/// </remarks>
	private static void ProcessCollectionToDispose(this IEnumerable items)
	{
		if (items.HasItems())
		{
			foreach (var item in items)
			{
				if (item is IDisposable disposeItem)
				{
					disposeItem.TryDispose();
				}
			}
		}
	}

	/// <summary>
	/// Adds the specified key and value to the dictionary if the key does not already exist.
	/// </summary>
	/// <typeparam name="TKey">The type of the keys in the dictionary.</typeparam>
	/// <typeparam name="TValue">The type of the values in the dictionary.</typeparam>
	/// <param name="collection">The dictionary to add to.</param>
	/// <param name="key">The key of the element to add.</param>
	/// <param name="value">The value of the element to add. It must not be null.</param>
	/// <returns>true if the key/value pair was added to the dictionary successfully; otherwise, false.</returns>
	/// <exception cref="ArgumentNullException">Thrown if <paramref name="collection" />, <paramref name="key" />, or <paramref name="value" /> is null.</exception>
	[Information("From .NET Core source.", author: "David McCarter", createdOn: "7/15/2020", UnitTestStatus = UnitTestStatus.Completed, BenchMarkStatus = BenchMarkStatus.NotRequired, Status = Status.Available)]
	public static bool AddIfNotExists<TKey, TValue>(this IDictionary<TKey, TValue> collection, TKey key, TValue value)
		where TKey : notnull
		where TValue : notnull
	{
		if (value is null)
		{
			return false;
		}

		key = key.ArgumentNotNull();
		collection = collection.ArgumentNotNull();

		if (collection.ContainsKey(key) is false)
		{
			collection.Add(key, value);
			return true;
		}

		return false;
	}


	/// <summary>
	/// Adds a range of key/value pairs to the dictionary. Each item from the specified collection is added to the dictionary
	/// if the key generated by the key selector does not already exist in the dictionary.
	/// </summary>
	/// <typeparam name="T">The type of the items in the collection.</typeparam>
	/// <typeparam name="TKey">The type of the keys in the dictionary.</typeparam>
	/// <typeparam name="TValue">The type of the values in the dictionary.</typeparam>
	/// <param name="collection">The dictionary to add the items to.</param>
	/// <param name="items">The collection of items to add to the dictionary.</param>
	/// <param name="key">A function to extract the key from each item.</param>
	/// <param name="value">A function to extract the value from each item.</param>
	/// <returns><c>true</c> if at least one item was added to the dictionary; otherwise, <c>false</c>.</returns>
	/// <exception cref="ArgumentNullException">Thrown if <paramref name="collection"/>, <paramref name="items"/>, <paramref name="key"/>, or <paramref name="value"/> is null.</exception>
	[DebuggerStepThrough]
	[Information(nameof(AddRange), "David McCarter", "11/21/2020", BenchMarkStatus = BenchMarkStatus.Completed, UnitTestStatus = UnitTestStatus.Completed, Status = Status.Available)]
	public static bool AddRange<T, TKey, TValue>(this IDictionary<TKey, TValue> collection, IEnumerable<T> items, Func<T, TKey> key, Func<T, TValue> value)
		where TKey : notnull
		where TValue : notnull
	{
		if (value is null)
		{
			return false;
		}

		key = key.ArgumentNotNull();
		items = items.ArgumentItemsExists();
		collection = collection.ArgumentNotNull();

		var added = false;

		foreach (var item in items)
		{
			var itemKey = key(item);
			var itemValue = value(item);
			if (!collection.ContainsKey(itemKey))
			{
				collection.Add(itemKey, itemValue);
				added = true;
			}
		}

		return added;
	}

	/// <summary>
	/// Disposes all disposable items within the dictionary. Each value in the dictionary that implements <see cref="IDisposable"/> will be disposed.
	/// </summary>
	/// <typeparam name="TKey">The type of the keys in the dictionary.</typeparam>
	/// <typeparam name="TValue">The type of the values in the dictionary, which must implement <see cref="IDisposable"/> if they are to be disposed.</typeparam>
	/// <param name="collection">The dictionary containing the items to dispose.</param>
	/// <exception cref="ArgumentNullException">Thrown if <paramref name="collection"/> is null.</exception>
	[Information(nameof(DisposeCollection), "David McCarter", "11/21/2020", UnitTestStatus = UnitTestStatus.None, BenchMarkStatus = BenchMarkStatus.None, Status = Status.Available)]
	public static void DisposeCollection<TKey, TValue>(this IDictionary<TKey, TValue> collection)
	{
		if (collection.HasItems())
		{
			ProcessCollectionToDispose(collection.Select(p => p.Value));
		}
	}

	/// <summary>
	/// Gets the value associated with the specified key or adds it if the key does not exist.
	/// </summary>
	/// <typeparam name="TKey">The type of keys in the dictionary.</typeparam>
	/// <typeparam name="TValue">The type of values in the dictionary.</typeparam>
	/// <param name="collection">The dictionary to search or add to.</param>
	/// <param name="key">The key of the value to get or add.</param>
	/// <param name="value">The value to add if the key does not exist.</param>
	/// <returns>The value associated with the specified key.</returns>
	/// <exception cref="ArgumentNullException">Thrown if <paramref name="collection" />, <paramref name="key" />, or <paramref name="value" /> is null.</exception>
	[Information("From .NET Core source.", author: "David McCarter", createdOn: "7/15/2020", UnitTestStatus = UnitTestStatus.Completed, BenchMarkStatus = BenchMarkStatus.Completed, Status = Status.Available)]
	public static TValue GetOrAdd<TKey, TValue>(this IDictionary<TKey, TValue> collection, TKey key, TValue value)
		where TKey : notnull
		where TValue : notnull
	{
		value = value.ArgumentNotNull();
		key = key.ArgumentNotNull();
		collection = collection.ArgumentNotNull();

		if (collection.TryGetValue(key, out var item) is false)
		{
			collection.Add(key, value);
			item = value;
		}

		return item;
	}

	/// <summary>
	/// Determines whether the specified action has items.
	/// </summary>
	/// <typeparam name="TKey">The type of the t key.</typeparam>
	/// <typeparam name="TValue">The type of the t value.</typeparam>
	/// <param name="collection">The dictionary.</param>
	/// <param name="action">The action.</param>
	/// <returns><c>true</c> if the specified action has items; otherwise, <c>false</c>.</returns>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	[Information(nameof(HasItems), author: "David McCarter", createdOn: "6/15/2022", UnitTestStatus = UnitTestStatus.Completed, BenchMarkStatus = BenchMarkStatus.Completed, Status = Status.Available, Documentation = "https://bit.ly/SpargineAug2022")]
	public static bool HasItems<TKey, TValue>(this IDictionary<TKey, TValue> collection, Func<KeyValuePair<TKey, TValue>, bool> action) => collection is not null && action is not null && collection.Any(action);

	/// <summary>
	/// Converts to a <see cref="IDictionary{TKey, TValue}" /> to a <see cref="ConcurrentDictionary{TKey, TValue}" />.
	/// </summary>
	/// <typeparam name="TKey">The type of the t key.</typeparam>
	/// <typeparam name="TValue">The type of the t value.</typeparam>
	/// <param name="collection">The collection.</param>
	/// <returns>ConcurrentDictionary&lt;TKey, TValue&gt;.</returns>
	[Information(nameof(ToSortedDictionary), "David McCarter", "7/23/2022", BenchMarkStatus = BenchMarkStatus.Completed, UnitTestStatus = UnitTestStatus.Completed, Status = Status.Available, Documentation = "https://bit.ly/SpargineAug2022")]
	public static ConcurrentDictionary<TKey, TValue> ToConcurrentDictionary<TKey, TValue>(this IDictionary<TKey, TValue> collection) => new(collection.ArgumentNotNull());

	/// <summary>
	/// Converts <see cref="IDictionary" /> to delimited string using <see cref="ObjectPool&lt;StringBuilder&gt;" /> to improve performance.
	/// </summary>
	/// <typeparam name="TKey">The type of the t key.</typeparam>
	/// <typeparam name="TValue">The type of the t value.</typeparam>
	/// <param name="collection">The list.</param>
	/// <param name="delimiter">The delimiter.</param>
	/// <returns>System.String.</returns>
	/// <example>Output:
	/// pfCfZQFGPWYXBlUvVHNb]ZjBO_LTbQBSCYb: pfCfZQFGPWYXBlUvVHNb]ZjBO_LTbQBSCYb,
	/// Dnadh[d`FP^SjNeChCvVuBXuEl^yVFUbKXsaacsCpJuxAscU: Dnadh[d`FP^SjNeChCvVuBXuEl^yVFUbKXsaacsCpJuxAscU.
	/// </example>
	[Information(nameof(ToDelimitedString), "David McCarter", "11/03/2020", "11/21/2020", BenchMarkStatus = BenchMarkStatus.Completed, Status = Status.Available, UnitTestStatus = UnitTestStatus.WIP, Documentation = "http://bit.ly/SpargineFeb2021")]
	public static string ToDelimitedString<TKey, TValue>(this IDictionary<TKey, TValue> collection, char delimiter = ControlChars.Comma)
	{
		if (collection.DoesNotHaveItems())
		{
			return string.Empty;
		}

		var sb = _stringBuilderPool.Get();

		try
		{
			foreach (var item in collection)
			{
				if (sb.Length > 0)
				{
					_ = sb.Append(delimiter.ToString(CultureInfo.CurrentCulture));
				}

				_ = sb.Append($"{item.Key}: {item.Value}".ToString(CultureInfo.CurrentCulture));
			}

			return sb.ToString().Trim();
		}
		finally
		{
			_stringBuilderPool.Return(sb);
		}
	}

	/// <summary>
	/// Converts a <see cref="IDictionary{TKey, TValue}" /> to <see cref="FrozenDictionary{TKey, TValue}" />.
	/// </summary>
	/// <typeparam name="TKey">The type of the t key.</typeparam>
	/// <typeparam name="TValue">The type of the t value.</typeparam>
	/// <param name="list">The list.</param>
	/// <returns>FrozenDictionary&lt;TKey, TValue&gt;.</returns>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	[Information(nameof(ToFrozenDictionary), "David McCarter", "6/3/2024", BenchMarkStatus = BenchMarkStatus.Completed, UnitTestStatus = UnitTestStatus.None, Status = Status.New, Documentation = "ADD URL")]
	public static FrozenDictionary<TKey, TValue> ToFrozenDictionary<TKey, TValue>(this IDictionary<TKey, TValue> list) => FrozenDictionary.ToFrozenDictionary(list);

	/// <summary>
	/// Converts <see cref="IDictionary{TKey, TValue}" /> to <see cref="ImmutableDictionary{TKey, TValue}" />.
	/// Validates that <paramref name="collection" /> is not null.
	/// </summary>
	/// <typeparam name="TKey">The type of the t key.</typeparam>
	/// <typeparam name="TValue">The type of the t value.</typeparam>
	/// <param name="collection">The values.</param>
	/// <returns>IImmutableDictionary&lt;TKey, TValue&gt;.</returns>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	[Information(nameof(ToImmutableDictionary), "David McCarter", "11/21/2020", BenchMarkStatus = BenchMarkStatus.Completed, UnitTestStatus = UnitTestStatus.Completed, Status = Status.Available)]
	public static ImmutableDictionary<TKey, TValue> ToImmutableDictionary<TKey, TValue>(this IDictionary<TKey, TValue> collection) => ImmutableDictionary.CreateRange(collection.ArgumentNotNull());

	/// <summary>
	/// Converts <see cref="IDictionary{TKey, TValue}" /> to <see cref="ImmutableSortedDictionary{TKey, TValue}" />.
	/// Validates that <paramref name="collection" /> is not null.
	/// </summary>
	/// <typeparam name="TKey">The type of the t key.</typeparam>
	/// <typeparam name="TValue">The type of the t value.</typeparam>
	/// <param name="collection">The values.</param>
	/// <returns>ImmutableSortedDictionary&lt;TKey, TValue&gt;.</returns>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	[Information(nameof(ToImmutableSortedDictionary), "David McCarter", "7/3/2024", BenchMarkStatus = BenchMarkStatus.Completed, UnitTestStatus = UnitTestStatus.None, Status = Status.New, Documentation = "ADD URL")]
	public static ImmutableSortedDictionary<TKey, TValue> ToImmutableSortedDictionary<TKey, TValue>(this IDictionary<TKey, TValue> collection) => ImmutableSortedDictionary.CreateRange(collection.ArgumentNotNull());

	/// <summary>
	/// Converts to a <see cref="IDictionary{TKey, TValue}" /> to a <see cref="ReadOnlyCollection{KeyValuePair}" />.
	/// </summary>
	/// <typeparam name="TKey">The type of the key.</typeparam>
	/// <typeparam name="TValue">The type of the value.</typeparam>
	/// <param name="dictionary">The dictionary.</param>
	/// <returns>ReadOnlyCollection&lt;KeyValuePair&lt;TKey, TValue&gt;&gt;.</returns>
	[Information(nameof(ToReadOnlyCollection), "David McCarter", "11/6/2023", BenchMarkStatus = BenchMarkStatus.Completed, UnitTestStatus = UnitTestStatus.None, Status = Status.NeedsDocumentation)]
	public static ReadOnlyCollection<KeyValuePair<TKey, TValue>> ToReadOnlyCollection<TKey, TValue>(this IDictionary<TKey, TValue> dictionary)
	{
		// Convert the dictionary to a list of KeyValuePair
		var list = new List<KeyValuePair<TKey, TValue>>(dictionary.ArgumentNotNull());

		// Create a ReadOnlyCollection from the list
		var readOnlyCollection = new ReadOnlyCollection<KeyValuePair<TKey, TValue>>(list);

		return readOnlyCollection;
	}

	/// <summary>
	/// Converts <see cref="IDictionary{TKey, TValue}" /> to <see cref="ReadOnlyDictionary{TKey, TValue}" />.
	/// Validates that <paramref name="collection" /> is not null.
	/// </summary>
	/// <typeparam name="TKey">The type of the t key.</typeparam>
	/// <typeparam name="TValue">The type of the t value.</typeparam>
	/// <param name="collection">The values.</param>
	/// <returns>ReadOnlyDictionary&lt;TKey, TValue&gt;.</returns>
	[Information(nameof(ToReadOnlyDictionary), "David McCarter", "6/3/2024", BenchMarkStatus = BenchMarkStatus.Completed, UnitTestStatus = UnitTestStatus.None, Status = Status.New, Documentation = "ADD URL")]
	public static ReadOnlyDictionary<TKey, TValue> ToReadOnlyDictionary<TKey, TValue>(this IDictionary<TKey, TValue> collection) => new(collection.ArgumentNotNull());


	/// <summary>
	/// Converts a <see cref="IDictionary{TKey, TValue}" /> to a <see cref="SortedDictionary{TKey, TValue}" />./&gt;
	/// Validates that <paramref name="collection" /> is not null.
	/// </summary>
	/// <typeparam name="TKey">The type of the t key.</typeparam>
	/// <typeparam name="TValue">The type of the t value.</typeparam>
	/// <param name="collection">The dictionary.</param>
	/// <returns>SortedDictionary&lt;TKey, TValue&gt;.</returns>
	[Information(nameof(ToSortedDictionary), "David McCarter", "6/27/2022", BenchMarkStatus = BenchMarkStatus.Completed, UnitTestStatus = UnitTestStatus.Completed, Status = Status.Available, Documentation = "https://bit.ly/SpargineAug2022")]
	public static SortedDictionary<TKey, TValue> ToSortedDictionary<TKey, TValue>(this IDictionary<TKey, TValue> collection) => new(collection.ArgumentNotNull());

	/// <summary>
	/// Upserts the specified item into the <see cref="IDictionary{TKey, TValue}" />.
	/// Validates that <paramref name="collection" /> and <paramref name="item" /> is not null.
	/// </summary>
	/// <typeparam name="TKey">The type of the t key.</typeparam>
	/// <typeparam name="TValue">The type of the t value.</typeparam>
	/// <param name="collection">The dictionary.</param>
	/// <param name="item">The item.</param>
	[Information(nameof(Upsert), "David McCarter", "5/2/2021", BenchMarkStatus = BenchMarkStatus.Completed, UnitTestStatus = UnitTestStatus.Completed, Status = Status.Available, Documentation = "https://bit.ly/SpargineJun2021")]
	public static void Upsert<TKey, TValue>(this IDictionary<TKey, TValue> collection, TValue item) where TValue : IDataModel<TValue, TKey>
	{
		if (item is null)
		{
			return;
		}

		collection = collection.ArgumentNotNull();

		if (collection.ContainsKey(item.Id))
		{
			_ = collection.Remove(item.Id);
		}

		collection.Add(item.Id, item);
	}

	/// <summary>
	/// Inserts or updates the item into a <see cref="IDictionary{TKey, TValue}" />.
	/// Validates that <paramref name="collection" />, <paramref name="key" /> and
	/// <paramref name="item" /> is not null.
	/// </summary>
	/// <typeparam name="TKey">The type of the t key.</typeparam>
	/// <typeparam name="TValue">The type of the t value.</typeparam>
	/// <param name="collection">The dictionary.</param>
	/// <param name="key">The key.</param>
	/// <param name="item">The value.</param>
	/// <returns>TValue.</returns>
	/// <exception cref="ArgumentNullException">dictionary</exception>
	/// <exception cref="ArgumentNullException">key</exception>
	/// <exception cref="ArgumentNullException">value</exception>
	/// <exception cref="ArgumentNullException">Input cannot be null or have no items in the collection.</exception>
	/// <exception cref="ArgumentNullException">Key cannot be null.</exception>
	[Information("From .NET Core source.", author: "David McCarter", createdOn: "7/15/2020", UnitTestStatus = UnitTestStatus.Completed, BenchMarkStatus = BenchMarkStatus.Completed, Status = Status.Available)]
	public static void Upsert<TKey, TValue>(this IDictionary<TKey, TValue> collection, TKey key, TValue item)
	{
		if (item is null)
		{
			return;
		}

		key = key.ArgumentNotNull();
		collection = collection.ArgumentNotNull();

		if (collection.ContainsKey(key))
		{
			_ = collection.Remove(key);
		}

		collection.Add(key, item);
	}

}
